# Overwrites mise configuration at .config/mise.toml
# Override GitHub backend tools with Go backend (GitHub backend doesn't work for these)
[tools]
"go:github.com/pulumi/pulumictl/cmd/pulumictl" = 'latest'
"go:github.com/pulumi/schema-tools/cmd/schema-tools" = "latest"
